<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByEmail($email)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:User p Where p.email= \''.$email.'\''
            )
            ->getResult();
    }
    public function findTrainings($userId)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:User p left join AppBundle:UserTraining ut with p.id = ut.userId left join AppBundle:Training t with ut.trainingId = t.id  Where p.id = ' . $userId
            )
            ->getResult();
    }

}
